const fruitsAndVegetables = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Watermelon",
    "Mango",
    "Pineapple",
    "Kiwi",
    "Blueberry",
    "Raspberry",
    "Cherry",
    "Pear",
    "Peach",
    "Plum",
    "Avocado",
    "Tomato",
    "Cucumber",
    "Carrot",
    "Broccoli",
    "Spinach",
    "Lettuce",
    "Cabbage",
    "Potato",
    "Sweet Potato",
    "Onion",
    "Garlic",
    "Bell Pepper",
    "Eggplant",
    "Zucchini",
    "Asparagus",
    "Celery",
    "Artichoke",
    "Cauliflower",
    "Cabbage",
    "Brussels Sprouts",
    "Radish",
    "Beetroot",
    "Turnip",
    "Pumpkin",
    "Squash",
    "Kale",
    "Swiss Chard",
    "Collard Greens",
    "Bok Choy",
    "Okra",
    "Green Beans",
    "Snow Peas",
    "Snap Peas",
    "Peas",
    "Cabbage",
    "Cauliflower",
    "Eggplant",
    "Bell Pepper",
    "Broccoli Rabe",
    "Fennel",
    "Leek",
    "Chives",
    "Scallions",
    "Sweet Corn",
    "Yam",
    "Rutabaga",
    "Daikon",
    "Jicama",
    "Ginger",
    "Artichoke",
    "Radicchio",
    "Watercress",
    "Mushroom",
  ];

const meats = [
  "Chicken",
  "Beef",
  "Pork",
  "Lamb",
  "Turkey",
  "Duck",
  "Bacon",
  "Ham",
  "Steak",
  "Ground Beef",
  "Pork Chops",
  "Pork Ribs",
  "Lamb Chops",
  "Lamb Shank",
  "Chicken Breast",
  "Chicken Thighs",
  "Chicken Drumsticks",
  "Whole Chicken",
  "Turkey Breast",
  "Turkey Legs",
  "Duck Breast",
  "Ground Pork",
  "Ground Lamb",
  "Ground Turkey",
  "Ground Chicken",
  "Pork Sausage",
  "Chicken Sausage",
  "Italian Sausage",
  "Hot Dogs",
  "Smoked Ham",
  "Pork Belly",
  "Beef Ribs",
  "Beef Brisket",
];

const seafood = [
    "Salmon",
    "Tuna",
    "Shrimp",
    "Crab",
    "Lobster",
    "Tilapia",
    "Cod",
    "Trout",
    "Sardines",
    "Mackerel",
    "Scallops",
    "Squid",
    "Clams",
    "Oysters",
    "Mussels",
    "Octopus",
  ];

  const dairiesAndEggs = [
    "Milk",
    "Butter",
    "Yogurt",
    "Heavy Cream",
    "Sour Cream",
    "Cream Cheese",
    "Cottage Cheese",
    "Whipped Cream",
    "Condensed Milk",
    "Evaporated Milk",
    "Almond Milk",
    "Coconut Milk",
    "Eggs",
  ];
  
  const cheeses = [
    "Cheese",
    "Cheddar Cheese",
    "Parmesan Cheese",
    "Mozzarella Cheese",
    "Swiss Cheese",
    "Brie Cheese",
    "Gouda Cheese",
    "Feta Cheese",
    "Bocconcini",
    "Blue Cheese",
    "Goat Cheese",
    "Provolone Cheese",
    "Havarti Cheese",
    "Gruyère Cheese",
    "Pepper Jack Cheese",
    "Camembert Cheese",
    "Emmental Cheese",
    "Manchego Cheese",
    "Ricotta Cheese",
    "Cottage Cheese",
    "Monterey Jack Cheese",
    "Haloumi Cheese" ,
  ];

  const charcuteries = [
    "Salami",
    "Prosciutto",
    "Chorizo",
    "Mortadella",
    "Pepperoni",
    "Capicola",
    "Soppressata",
    "Pancetta",
  ];

  const pantryItems = [
    "Flour",
    "Sugar",
    "Olive Oil",
    "Vegetable Oil",
    "Vinegar",
    "Soy Sauce",
    "Honey",
    "Maple Syrup",
    "Canned Tomatoes",
    "Tomato Paste",
    "Beans" ,
    "Lentils",
    "Chickpeas",
    "Coconut Milk",
    "Broth",
    "Canned Tuna",
    "Canned Salmon",
    "Canned Sardines",
    "Peanut Butter",
    "Almond Butter",
    "Nutella",
    "Jam",
    "Pickles",
    "Olives",
    "Capers",
    "Breadcrumbs",
    "Cereal",
    "Oats",
    "Popcorn",
    "Tea",
    "Coffee",
    "Cocoa Powder",
    "Spices (Cumin, Paprika, etc.)",
    "Herbs (Basil, Oregano, etc.)",
    "Vanilla Extract",
    "Baking Powder",
    "Baking Soda",
    "Yeast",
    "Canned Beans",
    "Dried Pasta",
  ];

  const boulangerieItems = [
    "Baguette",
    "Croissant",
    "White Bread",
    "Rye Bread",
    "Walnut Bread",
    "Raisin Bread",
    "Fougasse",
    "Bagel",
    "Pretzel",
    "English Muffin",
    "Ciabatta",
    "Sourdough Bread",
    "Whole Wheat Bread",
    "Multigrain Bread",
    "Rye Bread",
    "Brioche",
    "Spice Bread",
    "Almond Bread",
  ];

  const herbsAndSpices = [
    "Basil",
    "Thyme",
    "Rosemary",
    "Oregano",
    "Parsley",
    "Cilantro",
    "Dill",
    "Mint",
    "Sage",
    "Chives",
    "Coriander",
    "Cumin",
    "Paprika",
    "Cayenne Pepper",
    "Red Pepper Flakes",
    "Black Pepper",
    "White Pepper",
    "Cinnamon",
    "Nutmeg",
    "Cloves",
    "Ginger",
    "Turmeric",
    "Cardamom",
    "Mustard Seeds",
    "Fennel Seeds",
    "Celery Seeds",
    "Bay Leaves",
    "Allspice",
    "Marjoram",
    "Tarragon",
    "Fenugreek",
    "Caraway Seeds",
    "Poppy Seeds",
    "Saffron",
    "Vanilla",
    "Curry Powder",
    "Five-Spice Powder",
    "Garam Masala",
    "Herbes de Provence",
    "Italian Seasoning",
    "Za'atar",
    "Sumac",
  ];

  const saucesAndCondiments = [
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Barbecue Sauce",
    "Soy Sauce",
    "Worcestershire Sauce",
    "Hot Sauce",
    "Sriracha",
    "Honey Mustard",
    "Tartar Sauce",
    "Sweet Chili Sauce",
    "Teriyaki Sauce",
    "Hoisin Sauce",
    "Fish Sauce",
    "Oyster Sauce",
    "Basil Pesto",
    "Tomato Pesto",
    "Guacamole",
    "Salsa",
    "Hummus",
    "Tahini",
    "Vinegar",
    "Olive Oil",
    "Sesame Oil",
    "Sour Cream",
    "Ranch Dressing",
    "Blue Cheese Dressing",
    "Thousand Island Dressing",
    "Caesar Dressing",
    "Tzatziki",
    "Kimchi",
    "Harissa",
    "Sambal",
    "Chili Oil",
  ];

  const frozenItems = [
    "Mixed Vegetables",
    "Blueberries",
    "Pizza (Pepperoni)",
    "French Fries",
    "Chicken Nuggets",
    "Salmon Fillets",
    "Shrimp",
    "Ground Beef",
    "Ice Cream (Vanilla)",
    "Spinach",
    "Broccoli",
    "Strawberries",
    "Chicken Wings",
    "Tilapia Fillets",
    "Corn",
    "Green Beans",
    "Onion Rings",
    "Meatballs",
    "Turkey Burgers",
    "Mango Chunks",
  ];

  const PastaAndRiceTypes = [
    "Spaghetti",
    "Penne",
    "Fettuccine",
    "Macaroni",
    "Farfalle",
    "Rotini",
    "Rigatoni",
    "Linguine",
    "Orzo",
    "Lasagna",
    "Tagliatelle",
    "Gnocchi",
    "Ravioli",
    "Brown Rice",
    "White Rice",
    "Basmati Rice",
    "Jasmine Rice",
    "Sauvage Rice",
    "Medium Couscous",
    "Pearl Couscous",
    "Quinoa",
  ];